name: 4. Update Changelog

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["3. Create Release"]
  #   types:
  #     - completed

jobs:
  build_publish:
    name: Update Changelog
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Update changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          ./scripts/changelog.sh -c -p
